In [26]:
from NeuralNetwork import NeuralNetwork
from Layers.Linear import Linear
from Activations.Identity import Identity
from Activations.ReLU import Relu
from Loss.MSE import MSE
from Optimizers.MiniBatchGD import MiniBatchGD

import numpy as np

In [27]:
# XOR inputs and outputs for testing
X = np.array([[1, 1], [0, 0], [0, 1], [1, 0]])
y = np.array([[0], [0], [1], [1]])

In [28]:
nn = NeuralNetwork(
    [
    Linear((2, 2), Relu()),
    Linear((2, 1), Identity())
    ],
    criterion=MSE()
)

In [29]:
print(nn.predict(X))
nn.fit(X, y, 4, 200, 0.05, verbose=True)
print(nn.predict(X))

[[-0.02469298]
 [ 0.        ]
 [ 0.02336031]
 [-0.08654244]]
Epoch [0/200], Loss: 0.3497
Epoch [10/200], Loss: 0.2214
Epoch [20/200], Loss: 0.1725
Epoch [30/200], Loss: 0.0978
Epoch [40/200], Loss: 0.0428
Epoch [50/200], Loss: 0.0117
Epoch [60/200], Loss: 0.0032
Epoch [70/200], Loss: 0.0005
Epoch [80/200], Loss: 0.0001
Epoch [90/200], Loss: 0.0000
Epoch [100/200], Loss: 0.0000
Epoch [110/200], Loss: 0.0000
Epoch [120/200], Loss: 0.0000
Epoch [130/200], Loss: 0.0000
Epoch [140/200], Loss: 0.0000
Epoch [150/200], Loss: 0.0000
Epoch [160/200], Loss: 0.0000
Epoch [170/200], Loss: 0.0000
Epoch [180/200], Loss: 0.0000
Epoch [190/200], Loss: 0.0000
Epoch [200/200], Loss: 0.0000
[[3.40620909e-07]
 [2.96242185e-07]
 [9.99999844e-01]
 [9.99999903e-01]]


In [30]:
nn.show(detailed=True)

Fully Connected Layer: (2 inputs, 2 outputs) -> ReLU
Weights (column corresponds to output neuron): 
[[ 1.09289261 -0.97768899]
 [-1.09289256  0.97768896]]
Biases: 
[[ 3.56056826e-09 -8.50986952e-09]]
Fully Connected Layer: (2 inputs, 1 outputs) -> Identity
Weights (column corresponds to output neuron): 
[[0.91500263]
 [1.02281973]]
Biases: 
[[2.92984256e-07]]
