In [1]:
from NeuralNetwork import NeuralNetwork
from Layers.Linear import Linear
from Activations.Sigmoid import Sigmoid
from Activations.ReLU import Relu
from Loss.MSE import MSE

import numpy as np

In [2]:
# XOR inputs and outputs for testing
X = np.array([[1, 1], [0, 0], [0, 1], [1, 0]])
y = np.array([[0], [0], [1], [1]])

In [3]:
nn = NeuralNetwork(
    [Linear((2, 2), Relu(), dropout=0.8),
    Linear((2, 1), Sigmoid(), dropout=1)],
    criterion=MSE()
)

In [8]:
print(nn.predict(X))
nn.fit(X, y, batch_size=4, epochs=100, lr=0.1, verbose=True)
print(nn.predict(X))

[[0.19906421]
 [0.19906421]
 [0.94953497]
 [0.19906421]]
Epoch [0/100], Loss: 0.0207
Epoch [20/100], Loss: 0.3321
Epoch [40/100], Loss: 0.0220
Epoch [60/100], Loss: 0.0201
Epoch [80/100], Loss: 0.0210
Epoch [100/100], Loss: 0.1824
[[0.1903291 ]
 [0.1903291 ]
 [0.95833022]
 [0.96019396]]


In [9]:
nn.show(detailed=True)

Fully Connected Layer: (2 inputs, 2 outputs) -> ReLU
Weights (column corresponds to output neuron): 
[[ 1.65717313 -2.11069226]
 [-1.66108334  2.07277848]]
Biases: 
[[-0.00385017 -0.02198874]]
Fully Connected Layer: (2 inputs, 1 outputs) -> Sigmoid
Weights (column corresponds to output neuron): 
[[2.2408156 ]
 [1.78791196]]
Biases: 
[[-1.4478732]]
