In [1]:
from NeuralNetwork import NeuralNetwork
from Layers.Linear import Linear
from Activations.Sigmoid import Sigmoid
from Activations.ReLU import Relu
from Loss.MSE import MSE
from Optimizers.MiniBatchGD import MiniBatchGD

import numpy as np

In [2]:
# XOR inputs and outputs for testing
X = np.array([[1, 1], [0, 0], [0, 1], [1, 0]])
y = np.array([[0], [0], [1], [1]])

In [3]:
# Optimizer and Loss Objects?
nn = NeuralNetwork(
    [
    Linear((2, 1), Sigmoid()),
    Linear((1, 1), Sigmoid())
    ],
    loss=MSE, optimizer=MiniBatchGD(batch_size=10)
)

TypeError: Sigmoid.__init__() missing 1 required positional argument: 'factor'

In [6]:
print(X)

nn.fit(X, y)

print(nn.get_layer(0).W)
print(nn.get_layer(1).W)
print(nn.predict(X))

[[2 2]
 [3 3]
 [1 1]]

[[1 1]
 [3 3]
 [2 2]]

[[2 2]
 [1 1]
 [3 3]]

[[3 3]
 [2 2]
 [1 1]]

[[2 2]
 [1 1]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [3 3]
 [2 2]]

[[2 2]
 [1 1]
 [3 3]]

[[3 3]
 [1 1]
 [2 2]]

[[1 1]
 [2 2]
 [3 3]]

[[3 3]
 [1 1]
 [2 2]]

[[3 3]
 [1 1]
 [2 2]]

[[2 2]
 [1 1]
 [3 3]]

[[2 2]
 [1 1]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[3 3]
 [2 2]
 [1 1]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [3 3]
 [2 2]]

[[2 2]
 [3 3]
 [1 1]]

[[3 3]
 [1 1]
 [2 2]]

[[1 1]
 [3 3]
 [2 2]]

[[3 3]
 [1 1]
 [2 2]]

[[1 1]
 [3 3]
 [2 2]]

[[1 1]
 [3 3]
 [2 2]]

[[3 3]
 [2 2]
 [1 1]]

[[1 1]
 [3 3]
 [2 2]]

[[2 2]
 [1 1]
 [3 3]]

[[3 3]
 [2 2]
 [1 1]]

[[2 2]
 [1 1]
 [3 3]]

[[3 3]
 [2 2]
 [1 1]]

[[2 2]
 [1 1]
 [3 3]]

[[2 2]
 [1 1]
 [3 3]]

[[1 1]
 [3 3]
 [2 2]]

[[3 3]
 [1 1]
 [2 2]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[3 3]
 [1 1]
 [2 2]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [3 3]
 [2 2]]

[[1 1]
 [2 2]
 [3 3]]

[[2 2]
 [3 3]
 [1 1]]

[[3 3]
 [2 2]
 [1 1]]

[[1 1]
 [3 